### ISSUE TITLE
"ERR_REQUIRE_ESM"

### ISSUE THREAD

**Issue by specialdevivery** [michaelpalumbo/wspd#22]
i have successfully downloaded allhands but can't open it. i keep getting this error message:

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/viv/.npm-global/lib/node_modules/allhands/node_modules/public-ip/index.js from /Users/viv/.npm-global/lib/node_modules/allhands/bin/allhands.js not supported.
Instead change the require of index.js in /Users/viv/.npm-global/lib/node_modules/allhands/bin/allhands.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/viv/.npm-global/lib/node_modules/allhands/bin/allhands.js:7:18) {
  code: 'ERR_REQUIRE_ESM'
}

i have googled it and people have been able to resolve the problem with this code but somehow doesnt work for me ..

(async () => {
  const { fileTypeFromFile } = await import('file-type');

  const type = await fileTypeFromFile('fixture/fixture.gif');
  console.log(type);
})();

**Comment by specialdevivery** [comment]
> 

Btw i am running on mac os 12.6.1 Do you have any suggestions?

also thank you so much for supporting artists with your code, this seems like a great tool!

**Comment by michaelpalumbo** [comment]
Hi @specialdevivery thanks for the bug report and for wanting to try allhands!

I'll first try to replicate with a fresh install on my OSX machine. I too am running OSX Monterey. Will get back to you shortly

**Comment by michaelpalumbo** [comment]
aha. i am getting the same error!

```shell
/usr/local/lib/node_modules/allhands/bin/allhands.js:7
const publicIp = require('public-ip');
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/allhands/node_modules/public-ip/index.js from /usr/local/lib/node_modules/allhands/bin/allhands.js not supported.
Instead change the require of index.js in /usr/local/lib/node_modules/allhands/bin/allhands.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/allhands/bin/allhands.js:7:18) {
  code: 'ERR_REQUIRE_ESM'
}
```

Ok, i'll see what I can do.

**Comment by michaelpalumbo** [comment]
@specialdevivery try reinstalling allhands now. The issue stemmed from an experimental feature that I had implemented for a single performance and since then it seems no one has wanted to use, so I've just removed that feature and it seems to work again!

note that also the installation command is now
```shell
npm i --location=global allhands
```

**Comment by specialdevivery** [comment]
Hey thanks for getting back to me Michael!

Now I am getting this: zsh: command not found: allhands

I have followed procedures in this link ***@***.***/how-to-install-node-js-and-npm-with-macoss-new-terminal-zsh-e39b4a62d3d4 ***@***.***/how-to-install-node-js-and-npm-with-macoss-new-terminal-zsh-e39b4a62d3d4>

And still getting this message:  zsh: command not found: allhands

Vivan

**Comment by michaelpalumbo** [comment]
Hi @specialdevivery ah well that's progress, likely :D 

Can you tell me what is returned by the following command?

```shell
npm --version
```
